-- Tabela FATO_PREVISAO
CREATE SCHEMA IF NOT EXISTS stage;

CREATE OR REPLACE TABLE stage.fato_previsoes (
    WMO VARCHAR,
    DATA_MEDICAO DATE,
    PRECIPITACAO_MM FLOAT,
    PRESSAO_ATM_KPA FLOAT,
    TEMPERATURA_C FLOAT,
    UMIDADE_PORCENTAGEM INTEGER,
    VENTO_MPS FLOAT    
);




